import type { LocationId } from '../data/locations';
import type { LanguageCode } from '../player/types';
import type { TradeOffer, TradeProfile, VendorType } from './types';

type OfferInput = Omit<TradeOffer, 'acceptedBy' | 'description' | 'name'> & {
  acceptedBy?: VendorType[];
};

const offers: OfferInput[] = [
  {
    id: 'coffee',
    itemId: 'coffee',
    localeName: { en: 'Coffee', zh: '咖啡' },
    localeDescription: { en: 'A warm cup from the cafe counter.', zh: '咖啡店柜台上的热咖啡。' },
    iconKey: 'coffee',
    buyPrice: 6,
    sellPrice: 3,
    category: 'food',
    acceptedBy: ['cafe', 'inn'],
  },
  {
    id: 'latte',
    itemId: 'latte',
    localeName: { en: 'Latte', zh: '拿铁' },
    localeDescription: { en: 'Milk coffee for a longer conversation.', zh: '适合慢慢聊天的牛奶咖啡。' },
    iconKey: 'latte',
    buyPrice: 8,
    sellPrice: 4,
    category: 'food',
    acceptedBy: ['cafe'],
  },
  {
    id: 'sandwich',
    itemId: 'sandwich',
    localeName: { en: 'Sandwich', zh: '三明治' },
    localeDescription: { en: 'A quick meal for busy townsfolk.', zh: '给忙碌镇民准备的简餐。' },
    iconKey: 'sandwich',
    buyPrice: 10,
    sellPrice: 5,
    category: 'food',
    acceptedBy: ['cafe', 'restaurant', 'inn'],
  },
  {
    id: 'hot-meal',
    itemId: 'hotMeal',
    localeName: { en: 'Hot Meal', zh: '热餐' },
    localeDescription: { en: 'A filling plate from the restaurant.', zh: '餐厅出品的饱腹热餐。' },
    iconKey: 'hotMeal',
    buyPrice: 14,
    sellPrice: 7,
    category: 'food',
    acceptedBy: ['restaurant', 'inn'],
  },
  {
    id: 'soup',
    itemId: 'soup',
    localeName: { en: 'Soup', zh: '浓汤' },
    localeDescription: { en: 'Simple soup for hunger and comfort.', zh: '能填饱肚子也能暖身的浓汤。' },
    iconKey: 'soup',
    buyPrice: 9,
    sellPrice: 4,
    category: 'food',
    acceptedBy: ['restaurant'],
  },
  {
    id: 'fish-dish',
    itemId: 'fishDish',
    localeName: { en: 'Fish Dish', zh: '鱼料理' },
    localeDescription: { en: 'A coastal meal made with fresh fish.', zh: '用新鲜海鱼做的海边料理。' },
    iconKey: 'fishDish',
    buyPrice: 16,
    sellPrice: 8,
    category: 'food',
    acceptedBy: ['restaurant', 'dock'],
  },
  {
    id: 'bread',
    itemId: 'bread',
    localeName: { en: 'Bread', zh: '面包' },
    localeDescription: { en: 'Fresh bread from the bakery.', zh: '烘焙坊刚出炉的面包。' },
    iconKey: 'bread',
    buyPrice: 5,
    sellPrice: 2,
    category: 'food',
    acceptedBy: ['bakery', 'inn'],
  },
  {
    id: 'cake',
    itemId: 'cake',
    localeName: { en: 'Cake', zh: '蛋糕' },
    localeDescription: { en: 'A small cake for celebrations.', zh: '适合庆祝的小蛋糕。' },
    iconKey: 'cake',
    buyPrice: 12,
    sellPrice: 6,
    category: 'food',
    acceptedBy: ['bakery', 'cafe'],
  },
  {
    id: 'cookie',
    itemId: 'cookie',
    localeName: { en: 'Cookie', zh: '曲奇' },
    localeDescription: { en: 'A sweet snack from Poppy.', zh: 'Poppy 做的甜点小食。' },
    iconKey: 'cookie',
    buyPrice: 4,
    sellPrice: 2,
    category: 'food',
    acceptedBy: ['bakery', 'cafe'],
  },
  {
    id: 'apple',
    itemId: 'apple',
    localeName: { en: 'Apple', zh: '苹果' },
    localeDescription: { en: 'A crisp farm apple.', zh: '清脆的农场苹果。' },
    iconKey: 'apple',
    buyPrice: 4,
    sellPrice: 2,
    category: 'crop',
    acceptedBy: ['grocery', 'farm', 'restaurant', 'bakery'],
  },
  {
    id: 'tomato',
    itemId: 'tomato',
    localeName: { en: 'Tomato', zh: '番茄' },
    localeDescription: { en: 'Fresh produce for cooking.', zh: '适合做菜的新鲜番茄。' },
    iconKey: 'tomato',
    buyPrice: 4,
    sellPrice: 2,
    category: 'crop',
    acceptedBy: ['grocery', 'farm', 'restaurant'],
  },
  {
    id: 'carrot',
    itemId: 'carrot',
    localeName: { en: 'Carrot', zh: '胡萝卜' },
    localeDescription: { en: 'A sturdy vegetable from the field.', zh: '田地里收获的胡萝卜。' },
    iconKey: 'carrot',
    buyPrice: 4,
    sellPrice: 2,
    category: 'crop',
    acceptedBy: ['grocery', 'farm', 'restaurant'],
  },
  {
    id: 'berry',
    itemId: 'berry',
    localeName: { en: 'Berry', zh: '浆果' },
    localeDescription: { en: 'A handful of bright berries.', zh: '一小把鲜亮的浆果。' },
    iconKey: 'berry',
    buyPrice: 5,
    sellPrice: 2,
    category: 'crop',
    acceptedBy: ['grocery', 'farm', 'bakery'],
  },
  {
    id: 'pumpkin',
    itemId: 'pumpkin',
    localeName: { en: 'Pumpkin', zh: '南瓜' },
    localeDescription: { en: 'A heavy pumpkin from the farm.', zh: '农场里沉甸甸的南瓜。' },
    iconKey: 'pumpkin',
    buyPrice: 8,
    sellPrice: 4,
    category: 'crop',
    acceptedBy: ['grocery', 'farm', 'restaurant'],
  },
  {
    id: 'bandage',
    itemId: 'bandage',
    localeName: { en: 'Bandage', zh: '绷带' },
    localeDescription: { en: 'Basic clinic supplies.', zh: '诊所常备的基础用品。' },
    iconKey: 'bandage',
    buyPrice: 7,
    sellPrice: 3,
    category: 'item',
    acceptedBy: ['clinic'],
  },
  {
    id: 'tonic',
    itemId: 'tonic',
    localeName: { en: 'Tonic', zh: '补剂' },
    localeDescription: { en: 'A small bottle for recovery.', zh: '帮助恢复的小瓶补剂。' },
    iconKey: 'tonic',
    buyPrice: 13,
    sellPrice: 6,
    category: 'item',
    acceptedBy: ['clinic'],
  },
  {
    id: 'repair-kit',
    itemId: 'repairKit',
    localeName: { en: 'Repair Kit', zh: '修理包' },
    localeDescription: { en: 'Tools for simple repairs.', zh: '用于简单维修的工具包。' },
    iconKey: 'repairKit',
    buyPrice: 15,
    sellPrice: 7,
    category: 'item',
    acceptedBy: ['workshop', 'dock'],
  },
  {
    id: 'tool-parts',
    itemId: 'toolParts',
    localeName: { en: 'Tool Parts', zh: '工具零件' },
    localeDescription: { en: 'Spare parts from the workshop.', zh: '工坊里的备用零件。' },
    iconKey: 'toolParts',
    buyPrice: 11,
    sellPrice: 5,
    category: 'material',
    acceptedBy: ['workshop'],
  },
  {
    id: 'seed-pack',
    itemId: 'seedPack',
    localeName: { en: 'Seed Pack', zh: '种子包' },
    localeDescription: { en: 'Seeds ready for the farm plots.', zh: '可以播在农田里的种子包。' },
    iconKey: 'seedPack',
    buyPrice: 6,
    sellPrice: 3,
    category: 'crop',
    acceptedBy: ['farm', 'grocery'],
  },
  {
    id: 'produce-crate',
    itemId: 'produceCrate',
    localeName: { en: 'Produce Crate', zh: '蔬果箱' },
    localeDescription: { en: 'A crate of mixed farm produce.', zh: '一箱混合农产品。' },
    iconKey: 'produceCrate',
    buyPrice: 18,
    sellPrice: 9,
    category: 'crop',
    acceptedBy: ['farm', 'grocery', 'restaurant'],
  },
  {
    id: 'room-meal',
    itemId: 'roomMeal',
    localeName: { en: 'Room Meal', zh: '旅店餐食' },
    localeDescription: { en: 'A simple meal from the inn.', zh: '旅店提供的简餐。' },
    iconKey: 'roomMeal',
    buyPrice: 12,
    sellPrice: 6,
    category: 'service',
    acceptedBy: ['inn'],
  },
  {
    id: 'travel-snack',
    itemId: 'travelSnack',
    localeName: { en: 'Travel Snack', zh: '旅行小食' },
    localeDescription: { en: 'A snack for walking around town.', zh: '适合在镇上走动时吃的小食。' },
    iconKey: 'travelSnack',
    buyPrice: 6,
    sellPrice: 3,
    category: 'food',
    acceptedBy: ['inn', 'dock'],
  },
  {
    id: 'postcard',
    itemId: 'postcard',
    localeName: { en: 'Postcard', zh: '明信片' },
    localeDescription: { en: 'A coastal town postcard.', zh: '海边小镇的明信片。' },
    iconKey: 'postcard',
    buyPrice: 3,
    sellPrice: 1,
    category: 'item',
    acceptedBy: ['postOffice', 'studio'],
  },
  {
    id: 'bait',
    itemId: 'bait',
    localeName: { en: 'Fishing Bait', zh: '鱼饵' },
    localeDescription: { en: 'Bait for dockside fishing.', zh: '码头钓鱼用的鱼饵。' },
    iconKey: 'bait',
    buyPrice: 5,
    sellPrice: 2,
    category: 'item',
    acceptedBy: ['dock', 'grocery'],
  },
  {
    id: 'map-note',
    itemId: 'mapNote',
    localeName: { en: 'Map Note', zh: '地图笔记' },
    localeDescription: { en: 'A useful local route note.', zh: '记录本地路线的小笔记。' },
    iconKey: 'mapNote',
    buyPrice: 5,
    sellPrice: 2,
    category: 'information',
    acceptedBy: ['library', 'postOffice'],
  },
  {
    id: 'lesson-note',
    itemId: 'lessonNote',
    localeName: { en: 'Lesson Note', zh: '课程笔记' },
    localeDescription: { en: 'Short notes from the school.', zh: '学校里的简短课程笔记。' },
    iconKey: 'lessonNote',
    buyPrice: 5,
    sellPrice: 2,
    category: 'information',
    acceptedBy: ['school', 'library'],
  },
  {
    id: 'paint-kit',
    itemId: 'paintKit',
    localeName: { en: 'Paint Kit', zh: '绘画套装' },
    localeDescription: { en: 'Basic supplies from the studio.', zh: '工作室提供的基础绘画用品。' },
    iconKey: 'paintKit',
    buyPrice: 12,
    sellPrice: 6,
    category: 'item',
    acceptedBy: ['studio'],
  },
];

export const TRADE_CATALOG: TradeOffer[] = offers.map((offer) => ({
  ...offer,
  name: offer.localeName.en,
  description: offer.localeDescription.en,
  acceptedBy: offer.acceptedBy ?? [],
  maxStack: offer.maxStack ?? 99,
}));

export const TRADE_CATALOG_BY_ITEM_ID = Object.fromEntries(TRADE_CATALOG.map((offer) => [offer.itemId, offer])) as Record<
  string,
  TradeOffer
>;

const vendorDisplayNames: Record<VendorType, { en: string; zh: string }> = {
  cafe: { en: 'Cafe Counter', zh: '咖啡柜台' },
  restaurant: { en: 'Restaurant Kitchen', zh: '餐厅厨房' },
  clinic: { en: 'Clinic Service', zh: '诊所服务' },
  library: { en: 'Library Desk', zh: '图书馆柜台' },
  school: { en: 'School Guidance', zh: '学校服务' },
  studio: { en: 'Studio Desk', zh: '工作室柜台' },
  workshop: { en: 'Workshop Counter', zh: '工坊柜台' },
  grocery: { en: 'Grocery Counter', zh: '杂货柜台' },
  bakery: { en: 'Bakery Counter', zh: '烘焙柜台' },
  inn: { en: 'Inn Front Desk', zh: '旅店前台' },
  farm: { en: 'Farm Stand', zh: '农场摊位' },
  postOffice: { en: 'Post Office Counter', zh: '邮局柜台' },
  dock: { en: 'Dock Help', zh: '码头服务' },
};

export function createTradeProfile(locationId: LocationId, vendorType: VendorType): TradeProfile {
  return {
    enabled: true,
    vendorType,
    displayName: vendorDisplayNames[vendorType].en,
    locationId,
    offers: TRADE_CATALOG.filter((offer) => offer.acceptedBy.includes(vendorType)),
  };
}

export function localizedOfferName(offer: TradeOffer, language: LanguageCode): string {
  return offer.localeName[language] ?? offer.localeName.en;
}

export function localizedOfferDescription(offer: TradeOffer, language: LanguageCode): string {
  return offer.localeDescription[language] ?? offer.localeDescription.en;
}

export function localizedVendorName(vendorType: VendorType, language: LanguageCode): string {
  return vendorDisplayNames[vendorType][language] ?? vendorDisplayNames[vendorType].en;
}
