import type { ActionContract } from './ActionContract';
import type { Agent, WorldEvent } from './types';
import type { LocationId } from '../data/locations';
import { LOCATION_BY_ID } from '../data/locations';

export type DirectorIncidentType =
  | 'requestHelp'
  | 'lostItem'
  | 'shopShortage'
  | 'farmGathering'
  | 'rumorInvestigation'
  | 'publicGathering'
  | 'emergencyCheck';

export interface DirectorIncident {
  id: string;
  type: DirectorIncidentType;
  title: string;
  summary: string;
  locationId: LocationId;
  relatedAgentIds: string[];
  urgency: 'low' | 'normal' | 'high';
  suggestedActions: ActionContract[];
  source: 'llm' | 'fallback';
}

export interface DirectorContext {
  timeMinutes: number;
  timeLabel: string;
  agents: Agent[];
  events: WorldEvent[];
  playerName: string;
  language: 'en' | 'zh';
}

const FALLBACK_LOCATIONS: LocationId[] = ['cafe', 'farm', 'townSquare', 'clinic', 'library', 'dock'];

function stableIndex(seed: number, length: number): number {
  return Math.abs(Math.floor(seed)) % Math.max(1, length);
}

function fallbackIncidentId(timeMinutes: number, locationId: LocationId): string {
  return `director-${Math.floor(timeMinutes)}-${locationId}-${Math.floor(Math.random() * 10000)}`;
}

export class WorldDirector {
  createFallbackIncident(context: DirectorContext): DirectorIncident | undefined {
    const livingAgents = context.agents.filter((agent) => agent.isAlive !== false);
    if (livingAgents.length === 0) {
      return undefined;
    }

    const locationId = FALLBACK_LOCATIONS[stableIndex(context.timeMinutes / 37, FALLBACK_LOCATIONS.length)];
    const agent = livingAgents[stableIndex(context.timeMinutes + locationId.length, livingAgents.length)];
    const locationName = LOCATION_BY_ID[locationId].name;
    const zh = context.language === 'zh';
    const incidentType: DirectorIncidentType = locationId === 'farm' ? 'farmGathering' : locationId === 'townSquare' ? 'publicGathering' : 'requestHelp';
    const title = zh ? `${locationName} 的小镇事件` : `${locationName} town incident`;
    const summary = zh
      ? `${agent.name} 注意到 ${locationName} 有一件需要玩家确认的小事。`
      : `${agent.name} noticed something at ${locationName} that the player can verify.`;

    return {
      id: fallbackIncidentId(context.timeMinutes, locationId),
      type: incidentType,
      title,
      summary,
      locationId,
      relatedAgentIds: [agent.id],
      urgency: 'normal',
      source: 'fallback',
      suggestedActions: [
        {
          type: 'createTask',
          title,
          description: summary,
          contractKind: locationId === 'farm' ? 'gatherItem' : 'inspectLocation',
          targetLocationId: locationId,
          reason: summary,
          rewardGold: 8,
          rewardReputation: 4,
        },
        {
          type: 'shareBelief',
          summary,
          reason: zh ? '小镇事件导演生成的本地 fallback 事件。' : 'Local fallback incident generated by the town director.',
          targetAgentId: agent.id,
        },
      ],
    };
  }

  normalizeIncident(raw: unknown, context: DirectorContext): DirectorIncident | undefined {
    if (!raw || typeof raw !== 'object') {
      return undefined;
    }

    const value = raw as Record<string, unknown>;
    const locationId = typeof value.locationId === 'string' && value.locationId in LOCATION_BY_ID ? (value.locationId as LocationId) : undefined;
    if (!locationId) {
      return undefined;
    }

    const relatedAgentIds = Array.isArray(value.relatedAgentIds)
      ? value.relatedAgentIds.filter((id): id is string => typeof id === 'string' && context.agents.some((agent) => agent.id === id))
      : [];
    const type = typeof value.type === 'string' ? (value.type as DirectorIncidentType) : 'requestHelp';
    const urgency = value.urgency === 'low' || value.urgency === 'high' ? value.urgency : 'normal';
    const title = typeof value.title === 'string' && value.title.trim() ? value.title.trim() : `${LOCATION_BY_ID[locationId].name} incident`;
    const summary = typeof value.summary === 'string' && value.summary.trim() ? value.summary.trim() : title;
    const suggestedActions = Array.isArray(value.suggestedActions)
      ? (value.suggestedActions.filter((action) => action && typeof action === 'object') as ActionContract[])
      : [];

    return {
      id: typeof value.id === 'string' && value.id.trim() ? value.id.trim() : fallbackIncidentId(context.timeMinutes, locationId),
      type,
      title,
      summary,
      locationId,
      relatedAgentIds,
      urgency,
      suggestedActions,
      source: 'llm',
    };
  }
}
